using DealEvaluator.Application.DTOs.Comparable;
using DealEvaluator.Application.DTOs.Evaluation;
using DealEvaluator.Application.DTOs.Property;
using DealEvaluator.Application.DTOs.Rehab;

namespace DealEvaluator.Application.Interfaces;

/// <summary>
/// Service for managing property evaluation business logic
/// </summary>
public interface IPropertyService
{
    /// <summary>
    /// Creates a new property and performs initial evaluation
    /// </summary>
    /// <param name="dto">Property data from user input</param>
    /// <param name="userId">ID of the user creating the property</param>
    /// <returns>Created property with ID</returns>
    Task<PropertyDto> CreatePropertyAsync(CreatePropertyDto dto, string userId);

    /// <summary>
    /// Gets a property by ID
    /// </summary>
    Task<PropertyDto?> GetPropertyByIdAsync(int id);

    /// <summary>
    /// Gets all properties for a specific user
    /// </summary>
    Task<List<PropertyDto>> GetUserPropertiesAsync(string userId);

    /// <summary>
    /// Updates an existing property
    /// </summary>
    Task<PropertyDto> UpdatePropertyAsync(UpdatePropertyDto dto);

    /// <summary>
    /// Deletes a property
    /// </summary>
    Task DeletePropertyAsync(int id);

    /// <summary>
    /// Gets all evaluations for a specific property, ordered by most recent first
    /// </summary>
    /// <param name="propertyId">ID of the property</param>
    /// <returns>List of evaluations</returns>
    Task<List<EvaluationDto>> GetPropertyEvaluationsAsync(int propertyId);

    /// <summary>
    /// Gets the most recent evaluation for a property
    /// </summary>
    /// <param name="propertyId">ID of the property</param>
    /// <returns>Latest evaluation or null if none exist</returns>
    Task<EvaluationDto?> GetLatestEvaluationAsync(int propertyId);

    /// <summary>
    /// Gets all comparables for a specific property
    /// </summary>
    /// <param name="propertyId">ID of the property</param>
    /// <returns>List of comparables</returns>
    Task<List<ComparableDto>> GetComparablesAsync(int propertyId);

    /// <summary>
    /// Deletes a comparable
    /// </summary>
    /// <param name="comparableId">ID of the comparable to delete</param>
    Task DeleteComparableAsync(int comparableId);

    /// <summary>
    /// Creates a comparable from market data (Zillow property)
    /// </summary>
    /// <param name="dto">Comparable data from market data</param>
    /// <returns>Created comparable</returns>
    Task<ComparableDto> CreateComparableFromMarketDataAsync(CreateComparableDto dto);

    /// <summary>
    /// Creates a new evaluation for a property using the 70% rule
    /// </summary>
    /// <param name="dto">Evaluation input data including repair cost and comparable IDs</param>
    /// <returns>Created evaluation with calculated metrics</returns>
    Task<EvaluationDto> CreateEvaluationAsync(CreateEvaluationDto dto);

    /// <summary>
    /// Gets auto-generated rehab line items based on property details
    /// </summary>
    /// <param name="propertyId">ID of the property</param>
    /// <param name="userId">ID of the user (for template lookup)</param>
    /// <returns>List of auto-generated rehab line items</returns>
    Task<List<CreateRehabLineItemDto>> GetAutoGeneratedRehabEstimateAsync(int propertyId, string userId);
}